app = "library-management-web"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  LIBRARY_DATA_DIR = "/data"
  SPRING_PROFILES_ACTIVE = "prod"
  SERVER_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "library_data"
  destination = "/data"
